### ISSUE TITLE
GPURenderPassEncoder 多次 draw 时，是否保留多次渲染结果 

### ISSUE THREAD

**Issue by gyagp** [webatintel/webgraphicsforum#1]
By onsummer@foxmail.com
由 GPUCommandEncoder 创建 GPURenderPassEncoder，开始时会 setPipeline、setBindGroup 等操作，此时记录第一道 draw；紧接着再次 setBindGroup，再次 draw，目前有朋友遇到两次 draw 丢失一次的问题（暂时没要到源码），问题是：GPURenderPassEncoder 在 end 之前的多次 draw，是否 **只保留** 距离 end() 之前的最后一次 draw 到颜色附件中

**Comment by Jiawei-Shao** [comment]
> GPURenderPassEncoder 在 end 之前的多次 draw，是否 只保留 距离 end() 之前的最后一次 draw 到颜色附件中

不是这样的。如果设置的viewport和scissorRectangle只包括color attachment的一部分，那在这次draw之后viewport和scissor rectangle之外的部分就不会更改。

> 目前有朋友遇到两次 draw 丢失一次的问题（暂时没要到源码）

这需要结合具体的源码才能分析出原因了。如果viewport和scissorRectangle没变，那么第一次draw的结果就是会被第二次draw覆盖。

**Comment by wewindy** [comment]
已验证，同一个 GPURenderPassEncoder 在 end 之前进行多次 draw 操作，均会保留对应的在 colorAttachment 上
