### ISSUE TITLE
关于向 GPUBuffer 发送数据的 API 差异

### ISSUE THREAD

**Issue by gyagp** [webatintel/webgraphicsforum#3]
有两种方式向 GPUBuffer 传递 ArrayBuffer，
一种是创建时使用 mappedAtCreation，在创建时传递；
另一种是借助 GPUQueue 对象的 writeBuffer 方法，向已存在的 GPUBuffer 写入数据；
这两者除了 Timeline 不同，还有什么区别？（数据传输效率一样吗）
在每一帧中，通常能看到时候第二种来刷新 uniformBuffer；第一种反而比较见得多是 vertexBuffer 或 storageBuffer 的操作上

**Comment by jiangzhaoming** [comment]
实际上还有一种办法，就是在创建buffer后使用mapAsync。
从API角度，不同方法对buffer有不同的要求：
* 创建时使用 mappedAtCreation，对buffer的usage不做任何要求，但是要求buffer size必须为4的倍数（[Spec](https://www.w3.org/TR/webgpu/#dom-gpubufferusage-copy_dst)）。同时，一个mappedAtCreation的buffer必须unmap之后才能交由GPU使用，所以只能用来设置buffer的初始数据，之后需要在CPU端读写的话需要使用其他方法，比如使用writeBuffer，mapAsync，或者拷贝自/至另一个GPUBuffer。
* writeBuffer要求buffer必须具有COPY_DST的usage（[Spec](https://www.w3.org/TR/webgpu/#dom-gpuqueue-writebuffer)）。实际上writeBuffer是通过先创建一个内部的staging buffer，之后进行GPU上的buffer到buffer复制来实现的。
* mapAsync对buffer usage的要求最高([Spec](https://www.w3.org/TR/webgpu/#dom-gpubuffer-mapasync))，要通过mapAsync写buffer要求usage包含MAP_WRITE，而包含MAP_WRITE的buffer最多只能再包含COPY_SRC的usage，这样的buffer在GPU上只能用作向其他GPUBuffer拷贝数据的源而存在。同样的，要通过mapAsync读buffer要求usage包含MAP_READ，而包含MAP_READ的buffer最多只能再包含COPY_DST的usage，这样的buffer在GPU上只能用从其他GPUBuffer拷贝数据的目的地而存在。一般的（也就是，除了初始化之外的）CPU向GPU上buffer写数据的方法，是使用一个usage为`MAP_WRITE | COPY_SRC`的staging buffer，先mapAsync这个staging buffer，把CPU上的ArrayBuffer数据传递给它，之后unmap这个staging buffer，并使用GPU上的copyBufferToBuffer（[Spec](https://www.w3.org/TR/webgpu/#dom-gpucommandencoder-copybuffertobuffer)）来写入最终的GPUBuffer。从GPU向CPU读取数据也是这样。

在性能上，我记得mapAtCreation是最好的，writeBuffer的性能则不佳，实际上writeBuffer在内部隐含地实现了一个staging buffer，和上面mapAsync是一致的。WebGPU有一个[官方explainer文档](https://gpuweb.github.io/gpuweb/explainer/#buffer-mapping)有介绍这方面的具体内容。

关于为什么“第二种来刷新 uniformBuffer；第一种反而比较见得多是 vertexBuffer 或 storageBuffer 的操作上”，我不是很确定是否具有足够的代表性，可能是因为vertexBuffer（存放模型相关的顶点数据？）或者storageBuffer只需要一次初始化，之后数据保持不变（顶点信息）或者只需要GPU更新而不需要CPU重新写入，所以使用mapAtCreation赋CPU的初始值即可；uniformBuffer可能包含摄像机信息等，每帧都要更新，所以需要使用writeBuffer。

**Comment by Jiawei-Shao** [comment]
谷歌工程师写过的一篇[技术文档](https://github.com/toji/webgpu-best-practices/blob/main/buffer-uploads.md)里详细地介绍了WebGPU中buffer uploading各种方法的优劣和使用场景，非常值得参考！

**Comment by wewindy** [comment]
@jzm-intel @Jiawei-Shao 谢谢两位老师的解答，关于 `staging buffer` 这块缓存，它在物理上是在 GPU 核心晶片中，还是就是显存本身呢？

**Comment by jiangzhaoming** [comment]
> @jzm-intel @Jiawei-Shao 谢谢两位老师的解答，关于 `staging buffer` 这块缓存，它在物理上是在 GPU 核心晶片中，还是就是显存本身呢？

staging buffer应该就是分配的一块GPU显存，只不过专门[1]用于CPU-GPU间的数据传输。你说的在GPU核心中的缓存，应该是指CUDA中的shared memory和register，应该对应于WGSL中的workgroup变量和private、function变量。可以参考[WGSL Spec](https://gpuweb.github.io/gpuweb/wgsl/#address-space)。

[1]：这里的“专门”更多的是软件设计上的概念

**Comment by wewindy** [comment]
> > @jzm-intel @Jiawei-Shao 谢谢两位老师的解答，关于 `staging buffer` 这块缓存，它在物理上是在 GPU 核心晶片中，还是就是显存本身呢？
> 
> staging buffer应该就是分配的一块GPU显存，只不过专门用于CPU-GPU间的数据传输。你说的在GPU核心中的缓存，应该是指CUDA中的shared memory和register，应该对应于WGSL中的workgroup变量和private、function变量。可以参考[WGSL Spec](https://gpuweb.github.io/gpuweb/wgsl/#address-space)。

原来如此，谢谢解答。我在翻译计算着色器相关的文章 [WebGPU — All of the cores, none of the canvas(原文)](https://surma.dev/things/webgpu/) 时，有看到过这个 `shared memory`，大概是我搞混了，学艺不精。
