### ISSUE TITLE
希望有更多通用计算的实践分享（小案例）

### ISSUE THREAD

**Issue by gyagp** [webatintel/webgraphicsforum#4]

**Comment by gyagp** [comment]
Francois Beaufort写过一篇blog: [Get started with GPU Compute on the web](https://web.dev/gpu-compute/)
Austin Eng有一些sample: https://austin-eng.com/webgpu-samples/。像computeBoids, particles都是不错的samples.

**Comment by gyagp** [comment]
更多的例子，可以查看https://docs.qq.com/doc/DT2duTmloSXVTdFlz。

**Comment by xiaoiver** [comment]
我尝试用 WebGPU 移植一些已有的 CUDA 图分析和布局算法，例如 PageRank、SSSP、Fruchterman 布局等等。感兴趣的同学可以关注下～

个人的使用体验是，WGSL 对于 Compute Shader 的特性支持很不错，尤其是例如 `atomicMin` 这样的原子操作，有很多想象空间。甚至我在想能否实现一个 [cuGraph](https://github.com/rapidsai/cugraph) 呢？在大规模的节点边下性能提升挺明显的，但 JS 中数组太大会触发 [RangeError](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Errors/Invalid_array_length)，这可能是一个潜在的限制。

知乎文章：https://zhuanlan.zhihu.com/p/464654906
文档：https://g-next.antv.vision/zh/docs/api/gpgpu/webgpu-graph
示例：https://g-next.antv.vision/zh/examples/gpgpu#fruchterman

**Comment by xiaoiver** [comment]
> 更多的例子，可以查看[https://docs.qq.com/doc/DT2duTmloSXVTdFlz。](https://docs.qq.com/doc/DT2duTmloSXVTdFlz%E3%80%82)

文档貌似不存在了

**Comment by gyagp** [comment]
结尾的句号不是链接的一部分，应该是 https://docs.qq.com/doc/DT2duTmloSXVTdFlz

**Comment by wewindy** [comment]
附一篇我自己的翻译文 

[WebGPU — All of the cores, none of the canvas(原文)](https://surma.dev/things/webgpu/)

[WebGPU 计算管线、计算着色器（通用计算）入门案例：2D 物理模拟(中文翻译)](https://zhuanlan.zhihu.com/p/484448804)
