### ISSUE TITLE
如果BindGroupLayout绑定了多张纹理，那我们这边Shader执行时是否会排除没有用到但bindGroup了的纹理

### ISSUE THREAD

**Issue by lirongf** [webatintel/webgraphicsforum#7]
@group(0) @binding(1) var mySampler: sampler;
@group(0) @binding(2) var myTexture: texture_2d<f32>;
@group(0) @binding(3) var myTexture2: texture_2d<f32>;

@group(1) @binding(0) var<uniform> myColor2: vec4<f32>;
@fragment
fn main(
  @location(0) fragUV: vec2<f32>,
  @location(1) fragPosition: vec4<f32>
) -> @location(0) vec4<f32> {
  return textureSample(myTexture, mySampler, fragUV);
}

这段着色器运行时，是否会因为myTexture2没有用到而做不拷贝纹理资源的优化

**Comment by shaoboyan** [comment]
@jzm-intel @Jiawei-Shao 我隐约记得tint在把wgsl shader翻译成backend的shader的时候，是会把没有用到的bind resource忽略掉的。

**Comment by shaoboyan** [comment]
@lirongf 更新如下：

> @jzm-intel @Jiawei-Shao 我隐约记得tint在把wgsl shader翻译成backend的shader的时候，是会把没有用到的bind resource忽略掉的。

~~这个comment信息有误。~~

我用tint把提供的wgsl编译成了hlsl，结果如下：
更新后的wgsl（编译通过）
```
@group(0) @binding(1) var mySampler: sampler;
@group(0) @binding(2) var myTexture: texture_2d<f32>;
@group(0) @binding(3) var myTexture2: texture_2d<f32>;

@group(1) @binding(0) var<uniform> myColor2: vec4<f32>;
@fragment
fn main(
@location(0) fragUV: vec2<f32>,
@location(1) fragPosition: vec4<f32>
) -> @location(0) vec4<f32> {
return textureSample(myTexture, mySampler, fragUV);
}
```
（tint standalone生成的hlsl和chrome环境下不同）

~~使用的 tint的命令`tint.exe --format hlsl -o shader.hlsl shader.wgsl`~~

~~生成的hlsl:~~
```
SamplerState mySampler : register(s1);
Texture2D<float4> myTexture : register(t2);
Texture2D<float4> myTexture2 : register(t3);
cbuffer cbuffer_myColor2 : register(b0, space1) {
  uint4 myColor2[1];
};

struct tint_symbol_1 {
  float2 fragUV : TEXCOORD0;
  float4 fragPosition : TEXCOORD1;
};
struct tint_symbol_2 {
  float4 value : SV_Target0;
};

float4 main_inner(float2 fragUV, float4 fragPosition) {
  return myTexture.Sample(mySampler, fragUV);
}

tint_symbol_2 main(tint_symbol_1 tint_symbol) {
  const float4 inner_result = main_inner(tint_symbol.fragUV, tint_symbol.fragPosition);
  tint_symbol_2 wrapper_result = (tint_symbol_2)0;
  wrapper_result.value = inner_result;
  return wrapper_result;
}

```
~~可以看到生成的hlsl里面**未被使用的myTexture2还是存在的**~~


>这段着色器运行时，是否会因为myTexture2没有用到而做不拷贝纹理资源的优化

虽然tint生成的hlsl并没有做相关优化，但是hlsl的编译器是可能做类似优化的。用dxc编译上述hlsl得到的[最终结果](https://godbolt.org/z/qshGGP5GP)。可以看到在生成的dxil里面是没有`myTexture2`相关指令的

**Comment by shaoboyan** [comment]
@jzm-intel 提醒我tint standalone和chrome对wgsl的优化是有区别的，所以我又在chrome环境下dump了一下生成的hlsl，resource绑定相关部分如下：
```
texturedCube:1 /* Dumped generated HLSL */
SamplerState tint_symbol : register(s1);
Texture2D<float4> tint_symbol_1 : register(t2);

struct tint_symbol_6 {
  float2 tint_symbol_3 : TEXCOORD0;
  float4 tint_symbol_4 : TEXCOORD1;
};
struct tint_symbol_7 {
  float4 value : SV_Target0;
};

float4 tint_symbol_2_inner(float2 tint_symbol_3, float4 tint_symbol_4) {
  return (tint_symbol_1.Sample(tint_symbol, tint_symbol_3) * tint_symbol_4);
}

tint_symbol_7 tint_symbol_2(tint_symbol_6 tint_symbol_5) {
  const float4 inner_result = tint_symbol_2_inner(tint_symbol_5.tint_symbol_3, tint_symbol_5.tint_symbol_4);
  tint_symbol_7 wrapper_result = (tint_symbol_7)0;
  wrapper_result.value = inner_result;
  return wrapper_result;
}
```

可以看到chrome下webgpu也忽略了未使用的资源。
